export const bidsData = [
    {
        id: 1,
        productName: 'ABCXYZ',
        highestBidderName: 'Anderson John',
        totalBids: 78,
        currentPrice: '$1000.01',
    },
    {
        id: 2,
        productName: 'DEF123',
        highestBidderName: 'Sophia Lee',
        totalBids: 45,
        currentPrice: '$875.50',
    },
    {
        id: 3,
        productName: 'GHI456',
        highestBidderName: 'James Smith',
        totalBids: 92,
        currentPrice: '$1200.75',
    },
    {
        id: 4,
        productName: 'JKL789',
        highestBidderName: 'Emma Stone',
        totalBids: 63,
        currentPrice: '$950.00',
    },
    {
        id: 5,
        productName: 'MNO012',
        highestBidderName: 'Mia Clarke',
        totalBids: 110,
        currentPrice: '$1500.20',
    },
    {
        id: 6,
        productName: 'PQR345',
        highestBidderName: 'Lucas Miller',
        totalBids: 34,
        currentPrice: '$620.00',
    },
    {
        id: 7,
        productName: 'STU678',
        highestBidderName: 'Anna Belle',
        totalBids: 87,
        currentPrice: '$800.30',
    },
    {
        id: 8,
        productName: 'VWX901',
        highestBidderName: 'David Lee',
        totalBids: 56,
        currentPrice: '$730.50',
    },
    {
        id: 9,
        productName: 'YZA234',
        highestBidderName: 'Ava Davis',
        totalBids: 101,
        currentPrice: '$1125.75',
    },
    {
        id: 10,
        productName: 'BCD567',
        highestBidderName: 'Ella Johnson',
        totalBids: 68,
        currentPrice: '$900.40',
    },
    {
        id: 11,
        productName: 'EFG890',
        highestBidderName: 'Kyle Janifer',
        totalBids: 44,
        currentPrice: '$780.25',
    },
    {
        id: 12,
        productName: 'HIJ123',
        highestBidderName: 'Ali Cheema',
        totalBids: 76,
        currentPrice: '$980.10',
    },
    {
        id: 13,
        productName: 'KLM456',
        highestBidderName: 'Natalie Brooks',
        totalBids: 55,
        currentPrice: '$890.35',
    },
    {
        id: 14,
        productName: 'NOP789',
        highestBidderName: 'Zara Ahmed',
        totalBids: 89,
        currentPrice: '$1020.00',
    },
    {
        id: 15,
        productName: 'QRS012',
        highestBidderName: 'Charlotte Thomas',
        totalBids: 72,
        currentPrice: '$910.75',
    },
    {
        id: 16,
        productName: 'TUV345',
        highestBidderName: 'Liam Anderson',
        totalBids: 64,
        currentPrice: '$870.00',
    },
    {
        id: 17,
        productName: 'WXY678',
        highestBidderName: 'Owen Carter',
        totalBids: 82,
        currentPrice: '$1005.30',
    },
    {
        id: 18,
        productName: 'ZAB901',
        highestBidderName: 'Ethan Moore',
        totalBids: 53,
        currentPrice: '$750.60',
    },
    {
        id: 19,
        productName: 'CDE234',
        highestBidderName: 'Sophia Turner',
        totalBids: 95,
        currentPrice: '$1150.90',
    },
    {
        id: 20,
        productName: 'FGH567',
        highestBidderName: 'Jack Martin',
        totalBids: 60,
        currentPrice: '$820.25',
    },
];
